#!/usr/bin/env bash

code --install-extension hookyqr.beautify --force
code --install-extension eamodio.gitlens --force
code --install-extension ms-vscode.go --force
code --install-extension davidanson.vscode-markdownlint --force
code --install-extension equinusocio.vsc-material-theme --force
code --install-extension eg2.vscode-npm-script --force
code --install-extension christian-kohler.path-intellisense --force
code --install-extension ms-python.python --force
code --install-extension visualstudioexptteam.vscodein --force
code --install-extension vscode-icons-team.vscode-icons --force
code --install-extension redhat.java --force
code --install-extension ms-azuretools.vscode-docker --force
code --install-extension pkief.material-icon-theme --force
code --install-extension daylerees.rainglow --force
code --install-extension formulahendry.auto-close-tag --force
code --install-extension rogalmic.bash-debug --force
code --install-extension CoenraadS.bracket-pair-colorizer-2 --force
code --install-extension ms-azuretools.vscode-docker --force
code --install-extension ccimage.jsonviewer --force
code --install-extension emilast.LogFileHighlighter --force
code --install-extension IBM.output-colorizer --force
code --install-extension ionutvmi.path-autocomplete --force
code --install-extension jebbs.plantuml --force
code --install-extension esbenp.prettier-vscode --force
code --install-extension ms-python.python --force
code --install-extension mechatroner.rainbow-csv --force
code --install-extension Tyriar.sort-lines --force
code --install-extension wayou.vscode-todo-highlight --force
code --install-extension shardulm94.trailing-spaces --force
code --install-extension vscode-icons-team.vscode-icons --force